### ISSUE TITLE
This cache store does not support tagging.

### ISSUE THREAD

**Issue by kickthemooon** [Zizaco/entrust#468]
Happend after update to 5.2.

Not sure if this has something to do with entrust but in the list I see that this issue has something to do with Repository->tags('role_user') and
Cache::tags('role_user') in EntrustUserTrait.php line 29

```
BadMethodCallException in C:\wamp\www\baseapp\vendor\laravel\framework\src\Illuminate\Cache\Repository.php line 380:
This cache store does not support tagging.
in Repository.php line 380
at Repository->tags('role_user')
at call_user_func_array(array(object(Repository), 'tags'), array('role_user')) in CacheManager.php line 296
at CacheManager->__call('tags', array('role_user')) in Facade.php line 216
at CacheManager->tags('role_user') in Facade.php line 216
at Facade::__callStatic('tags', array('role_user')) in EntrustUserTrait.php line 29
at Cache::tags('role_user') in EntrustUserTrait.php line 29
at User->save() in EloquentUserProvider.php line 78
```

Anyone else had this one?
And ideas?

**Comment by kickthemooon** [comment]
I think I found the issue, maybe.
```
Note: Cache tags are not supported when using the file or database cache drivers. Furthermore, when using multiple tags with caches that are stored "forever", performance will be best with a driver such as memcached, which automatically purges stale records.
```
and here is the entrust trait:
```
//Big block of caching functionality.
    public function cachedRoles()
    {
        $userPrimaryKey = $this->primaryKey;
        $cacheKey = 'entrust_roles_for_user_'.$this->$userPrimaryKey;
        return Cache::tags(Config::get('entrust.role_user_table'))->remember($cacheKey, Config::get('cache.ttl'), function () {
            return $this->roles()->get();
        });
    }
    public function save(array $options = [])
    {   //both inserts and updates
        parent::save($options);
        Cache::tags(Config::get('entrust.role_user_table'))->flush();
    }
    public function delete(array $options = [])
    {   //soft or hard
        parent::delete($options);
        Cache::tags(Config::get('entrust.role_user_table'))->flush();
    }
    public function restore()
    {   //soft delete undo's
        parent::restore();
        Cache::tags(Config::get('entrust.role_user_table'))->flush();
    }
```

Could this be the issue and how can it be dealt with?

**Comment by lcdss** [comment]
Yes, Laravel file and database drivers doesn't support tags. What you can do to while developing is change the driver to array in your .env file.
`CACHE_DRIVER=array`

**Comment by kickthemooon** [comment]
i saw that already, but was changing the thing in config/cache.php lol
forgot the env setting, works great now, thanks.

**Comment by adityaraval** [comment]
should i change both settings?
.env file

>  CACHE_DRIVER=array

and in config/cache.php

    'default' => env('CACHE_DRIVER', 'array'),


I have tried for all still i am getting error regarding cache

BadMethodCallException in Repository.php line 367:
This cache store does not support tagging.

**Comment by unpatrice** [comment]
I have the same issue with Laravel 5.1.29 when trying this command : 
echo Entrust::hasRole('role-name');

BadMethodCallException in Repository.php line 294:
This cache store does not support tagging.

**Comment by unpatrice** [comment]
I changed to composer to "zizaco/entrust": "dev-laravel-5" and it solved it.

Blade directives 
~~~
@if(Entrust::hasRole('admin'))
    ....
@endif
~~~
working but 
~~~
@role('admin'))
    <div>This is visible to users with the admin role. Gets translated to role('admin')</div>
@endrole
~~~
not.

**Comment by adityaraval** [comment]
I m facing problem while i am registering new user and setting role for that user in controller

```
/**
     * Create a new user instance after a valid registration.
     *
     * @param  array  $data
     * @return User
     */
    protected function create(array $data)
    {
        $user=User::create([
            'firstname' => $data['firstname'],
            'lastname' => $data['lastname'],
            'gender' => $data['gender'],
            'birthdate' => date("Y-m-d", strtotime($data['birthdate'])),
            'email' => $data['email'],
            'password' => bcrypt($data['password']),
            'temple' => $data['temple'],
            'refname' => $data['refname'],
            'refcontact' => $data['refcontact'],
        ]);
       $user->attachRole(2); // parameter can be an Role object, array, or id

        return $user;

    }
```

**Comment by case90** [comment]
I am still the same error, even after update .env file and change to composer to "zizaco/entrust": "dev-laravel-5" :(

**Comment by justinr1234** [comment]
+1 when trying to create users with attached foreign key for role_id from the roles table.

**Comment by haakym** [comment]
Changing cache driver to array: `CACHE_DRIVER=array` fixed this issue for me, I am also creating user and attaching role directly after and have no issue. I'm using laravel 5.2.

**Comment by PENDOnl** [comment]
`CACHE_DRIVER=array` is just a temporary fix for development, isn't it? I'd like to keep using the file cache driver on the production site but that isn't working right now. Any news on this issue?

Occured to me when registering a new user on a new L5.2 installation with `"zizaco/entrust": "5.2.x-dev",`

**Comment by mwhardesty** [comment]
This is also an issue for me. I'm on L5.2 using "zizaco/entrust": "5.2.x-dev"

**Comment by Jolora** [comment]
Same problem here with 5.2 using "zizaco/entrust": "5.2.x-dev"

**Comment by raphagodoi** [comment]
Same problem here with 5.2

**Comment by djdiramio** [comment]
I'm having issues with this in 5.2 when I moved to production.  Is there a solution for production?

**Comment by hafeez1042** [comment]
+1

**Comment by iodigitalsec** [comment]
+1

**Comment by yahyazini** [comment]
+1

**Comment by birdshark** [comment]
+2

**Comment by w3hacker** [comment]
+3

**Comment by huangered** [comment]
.env CACHE_DRIVER=array
is worked for  me

**Comment by pxpm** [comment]
Using array as a cache driver works, but it's an workaround and should not be used in production. Any other solution to don't use array as a cache driver? thanks in advance.

**Comment by djdiramio** [comment]
@pxpm - Changing to memcached fixed the problem for me as I didn't want to use array in production.  It does look like this has been addressed though so check out this: https://github.com/Zizaco/entrust/pull/547

**Comment by Jolora** [comment]
Ultimately I made the decision that the best option was to start using memcached.

**Comment by MateenRay** [comment]
"zizaco/entrust": "dev-laravel-5" will solve this problem

**Comment by eduardoarandah** [comment]
change to cache array

`CACHE_DRIVER=array`

and **dont forget** to run 

`php artisan config:cache`

**Comment by legendweny** [comment]
+!

**Comment by shawnsandy** [comment]
+5

**Comment by CaptainHypertext** [comment]
Using the `array` cache driver locally is not a solution, that just disables caching.  So while `Cache` methods will work, no data will actually be available between requests.

**Comment by eduardoarandah** [comment]
This cache feature I guess is perfect for big/performant systems.

But for something quick I just switched to
https://github.com/caffeinated/shinobi

Because is quicker to configure and already has a GUI and I'm lazy.

**Comment by ndflydog** [comment]
+1

**Comment by marwanzak** [comment]
+1

**Comment by halloei** [comment]
+1

**Comment by ReDraft** [comment]
+1

**Comment by hendisantika** [comment]
.env CACHE_DRIVER=array
is worked for me


Thanks

**Comment by dmdnkv** [comment]
It is possible to use apc, memcached or redis.

> CACHE_DRIVER=apc
> CACHE_DRIVER=memcached
> CACHE_DRIVER=redis

Moreover, they are all preconfigured in `homestead` environment.

**Comment by manishios** [comment]
.env CACHE_DRIVER=array
works for me but since this is not a permanent fix. Have one of us found a permanent fix for this.
Thanks

**Comment by marcoraddatz** [comment]
@eduardoarandah, @CaptainHypertext: As far as I know doesn't `array` disable the cache, but restricts it to a single request only.

I just forked the project and played around a bit. Following code reduced my queries dramatically (40+ queries to 8):

```
/**
 * Big block of caching functionality.
 *
 * @return \Illuminate\Database\Eloquent\Collection
 */
public function cachedPermissions()
{
    $rolePrimaryKey = $this->primaryKey;
    $cacheKey       = 'entrust_permissions_for_role_' . $this->$rolePrimaryKey;

    if (Cache::getStore() instanceof TaggableStore) {
        return Cache::tags(Config::get('entrust.permission_role_table'))->remember($cacheKey, Config::get('cache.ttl', 60), function () {
            return $this->perms()->get();
        });
    }
    else {
        return Cache::store('array')->remember($cacheKey, 0, function () {
            return $this->perms()->get();
        });
    }
}
```
and
```
/**
 * Big block of caching functionality.
 *
 * @return \Illuminate\Database\Eloquent\Collection
 */
public function cachedRoles()
{
    $userPrimaryKey = $this->primaryKey;
    $cacheKey       = 'entrust_roles_for_user_' . $this->$userPrimaryKey;

    if (Cache::getStore() instanceof TaggableStore) {
        return Cache::tags(Config::get('entrust.role_user_table'))->remember($cacheKey, Config::get('cache.ttl', 60), function () {
            return $this->roles()->get();
        });
    }
    else {
        return Cache::store('array')->remember($cacheKey, 0, function () {
            return $this->roles()->get();
        });
    }
}
```

Full code is at https://github.com/marcoraddatz/entrust – will provide it soon via packagist.

**Comment by thanhdevapp** [comment]
@marcoraddatz Your version forked merge to master? how i can use some issues you fixed

**Comment by roshimon** [comment]
CACHE_DRIVER=array worked for me as well on Laravel 5.2

**Comment by pjmartorell** [comment]
@marcoraddatz @thanhdevapp @kickthemooon All these errors/alerts are fixed in branch `master`. Do a require of `"zizaco/entrust": "dev-master"` to install it. You can check the changes done to solve it in https://github.com/Zizaco/entrust/pull/547.

**Comment by marcoraddatz** [comment]
@thanhdevapp  You can either fork it or use it temporary until changes/PR are merged into this package.

Add this to your composer.json
```
  "repositories": [
    {
      "type": "vcs",
      "url": "git@github.com:marcoraddatz/entrust.git"
    }
  ],
  "require": {
    "marcoraddatz/entrust": "dev-master",
  }
```

@pjmartorell: Thanks for providing your solution! Yes, the exceptions are fixed, but a cache for non-taggable providers is still missing. 

Right now, when using `array` or `file` caches, Entrust will query the DB every time a permission/role is requested—even though it's exactly the same query. To avoid that, I extended your code a bit, so that they are at least cached for the request.

**Comment by pjmartorell** [comment]
@marcoraddatz Nice, but if there is a 'file' store defined, with your implementation, you are forcing the user to use an 'array' store.

**Comment by marcoraddatz** [comment]
@pjmartorell Yes, that is intended, because if the user would use the file cache, we would have to clean it up on changes. When using the array only, it's only valid for the request, so there's no need to clean it up later. :)

**Comment by fcarentz** [comment]
I changed to composer.json to "zizaco/entrust": "dev-laravel-5"  as well as updated my .env file and config/cache.php file to be CACHE_DRIVER array. Problem was solved for me

**Comment by geraldarcega** [comment]
Hi all. I changed my .env CACHE_DRIVER=array and run php artisan config:cache but unfortunately after it I got a new error which is Fatal error: Uncaught ReflectionException: Class log does not exist in vendor/laravel/framework/src/Illuminate/Container/Container.php on line 73

Is there anyone here experience the same problem, or any knowledge on how to fix this, please help. Thanks!

**Comment by omarjebari** [comment]
See #422 for a fix that doesnt involve changing the cache driver.
It tells you to use the following version "dev-laravel-5" in your composer.json

**Comment by wdgwgz** [comment]
+1

**Comment by ukadev** [comment]
CACHE_DRIVER=array worked for me as well on Laravel 5.3.17

**Comment by vhanla** [comment]
Will it be fixed?
Still switching to array in Laravel 5.3.19.

**Comment by rBrda** [comment]
I can confirm that the issue still exists. Laravel v5.3.24, Entrust 5.2.x-dev.

Whenever I try to logout I get the following exception thrown:

```
BadMethodCallException in Repository.php line 391:
This cache store does not support tagging.
```

**Comment by ngooide** [comment]
CACHE_DRIVER=array work for me on L5.3.24
remember to restart your web server.

**Comment by Sieabah** [comment]
Switching to array is not a solution if you use the DB for a cache in production.

**Comment by vhanla** [comment]
Laratrust doesn't have that issue, which is based on Entrust.

**Comment by myrage18** [comment]
I'm having same issues, I really wish to have a fix on this so we can use default cache driver "file" of Laravel. I've seen it working on a different project with cache driver. I don't know how the author succeed making it work with cache driver = "file". Can we expect a fix for this issue on a fresh Laravel installation with Entrust ?

**Comment by rBrda** [comment]
I personally switched to Laratrust since it supports the "file" cache driver. It's pretty neat and has the same functionality like Entrust.

**Comment by myrage18** [comment]
Ok thanks, would it still be compatible with Entrust permissions_roles, since our project is not starting... I was checking to fix cache driver issue before production. We'll probably use memcached too

**Comment by rBrda** [comment]
If you're talking about the database tables, it's all the same. I haven't changed anything. And as far as I know, the methods to add/remove and update roles and permissions are the same mostly. Give it a try.

**Comment by ceylanb** [comment]
+1

**Comment by jonathancbarros** [comment]
Isn't there a release with the fix for this issue yet?

**Comment by kneipp** [comment]
+1

**Comment by veneliniliev** [comment]
+1

**Comment by maherelgamil** [comment]
+1

**Comment by hobbsgoblin** [comment]
+1

**Comment by stuartcusackie** [comment]
I was getting this same error as a result of a mis-configured installation of the Torann/laravel-geoip package.

This package uses cache_tags by default and I have to comment out a line in the geoip.php vendor config file after publishing the package. Like so:

` //'cache_tags' => ['torann-geoip-location'],`

Problem solved for me.

**Comment by i7sn** [comment]
its work 

thanks

**Comment by RSAAUTHENTICATIONPANKAJ** [comment]
Try to config cache ( php artisan config:cache ) for laravel

**Comment by edwinwongnetccentric** [comment]
if you're using homestead it has redis installed, just CACHE_DRIVER=redis

**Comment by jonjie0317** [comment]
@lcdss is it safe to use `array`? You said that "While developing". Then what if in the production? Thanks for your answer.

**Comment by DiakosavvasN** [comment]
I have `CACHE_DRIVER=array` and works fine !!! However I want to use `CACHE_DRIVER=memcached`.
I've tried to add on the .env file the memcached but it doesn't work. Keep saying `Class 'Memcached' not found`. I've tried to download memcached but I dont have apt-get in my shared server. What can I do ? Anyone can help me ?

**Comment by jonjie0317** [comment]
@DiakosavvasN its a difficult problem with entrust, but hope, they will fix it soon. Anyways, you may try other package if you want to, because `CACHE_DRIVER=array` is not the right way to solve this kind of issue according to my research.

**Comment by notflip** [comment]
Any update on this?

**Comment by flymorn** [comment]
Just change:
"zizaco/entrust": "5.2.x-dev"
TO
"zizaco/entrust": "dev-master"

then solved.

"dev-master" have Merged [pjmartorell:fix-cache-tags](https://github.com/Zizaco/entrust/pull/547)

**Comment by mkhsojib** [comment]
Just change:
"zizaco/entrust": "5.2.x-dev"
to
"zizaco/entrust": "dev-master"

Thats it

**Comment by arslanramay** [comment]
> Yes, Laravel file and database drivers doesn't support tags. What you can do to while developing is change the driver to array in your .env file.
> `CACHE_DRIVER=array`

Worked 100%. Thanks for the tip!

**Comment by tayyabhussainit** [comment]
`CACHE_DRIVER=file `
doesn't support tagging, and changing it to `array` is not a best solution, as array cache is only limited to a request,
better to use `redis` or `memcahce`
